### ISSUE TITLE
Can we integrate PF6 with Latest version of AngularFaces ?

### ISSUE THREAD

**Issue by subodhcjoshi82** [stephanrauh/AngularFaces#72]
Hi i am using PF6 in my web project with JSF2.2 Can i use AngularFaces latest release(AngularFaces 2.1.9 (Sept 24, 2015)) with PF6?

What about Next release of AngularFaces and date you decided last year too many release with in short span of time but this year no single release any particular reason behind this or you are going to make a major release 3.0.0  ?

Also i read 

> A future version of AngularFaces will support Dart and AngularDart, but I've postponed Dart support because I'm waiting for a couple of announced breaking changes in AngularDart.

So future version of AngularFaces will be more towards AngularDart and now AngularJS. ?

One Last question

Any AngularJS features or any third party directive/lib will be supported by AngularFaces and if i am using Angularfaces these thing can be easily integrated with JSF/PF project?

**Comment by stephanrauh** [comment]
Let's start with the first and the last question. I don't see any obstacle to using either PrimeFaces 6 or any third-party AngularJS library with AngularFaces. Everything should run out of the box, even without additional support from AngularFaces. If you run into trouble, especially with PrimeFaces 6, just report it, so I can see how to fix it.

**Comment by stephanrauh** [comment]
As for the third question: as far as I can see, the Dart language has silently been abandoned. The Angular2 team still consider Dart a target language, but I'm under the impression both the developer community and Google have decided to drop Dart. The core idea of Dart was to introduce a second virtual machine, which ruined JavaScript interoperability, and that was that. In a way, it's a pity, but I think TypeScript is an equally good alternative, so nothing is lost.

**Comment by stephanrauh** [comment]
Now for the difficult question. The sad truth is that the download figures of AngularFaces are disappointing. Most developers are repelled from the complexity of two different lifecycles (JSF and Angular). On the other hand, there seems to be a small but loyal community of happy AngularFaces users, so I don't want to simply drop it. But I have to admit I concentrate almost exclusively on BootsFaces. That's absorbing my spare time, so I need your help to carry on the AngularFaces story. Would you like to participate with the project?

The next big version of AngularFaces should support Angular2 instead of AngularJS 1.x. Unfortunately, Angular2 doesn't allow the tricks I used in AngularFaces <= 2.1, so an all-new approach is needed. I suppose the best approach is to inverse the control: The Angular2 application should trigger the JSF engine directly. The current version of AngularFaces tries to control the AngularJS engine from the server side, which is difficult because AngularJS hasn't been designed with being remotely controlled in mind.

**Comment by subodhcjoshi82** [comment]
I don't have any issue to support AngularFaces but one doubt on my self can I support ? Now let me explain you why i have doubt myself firstly i am not good in JS and AngularJS just started but yes in JSF   am developed couple of projects and still love to work in JSF. So now you can decide Can i still good to support AngularFaces as you are creator of AngularFaces so you know a,b,c of both the technology .

Now come to  your first reply i am starting a fresh project so thinking to use AngularFaces with Primefaces and reason behind this i can't use directly AngularJS reason i already mentioned above.

Now why we choose the AngularFaces 

- My Application would be one page application

- Look like JS framework going to more popular than server side frameworks in near future

Lets share some gmailids so we can talk further . What do you think let me know

Thanks

**Comment by stephanrauh** [comment]
I think I've got a better idea. Instead of giving you my email address, I'd like to point you to https://gitter.im/TheCoder4eu/BootsFaces-OSP. That's the BootsFaces chat, but I suppose people won't mind if you ask an AngularFaces question. If they do, tell them I've led you there :). The BootsFaces chat has the advantage that several other developers can give you hints.

BTW, you're right, your lack of experience doesn't exactly qualify you as an AngularFaces core developer. But that doesn't mean you can't help. JavaScript is a language like every other language, you can learn it with little effort. So, if you find an error or have a suggestion, feel free to submit a pull request.

One last point: it's possible to create a SPA with BootsFaces (http://www.beyondjava.net/blog/single-page-applications-with-bootsfaces/). The same recipe should work with PrimeFaces, probably even better, because the PrimeFaces team care about their JavaScript memory leaks several versions ago.

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
